-- FREE_COMMENT 데이터 삽입
INSERT INTO FREE_COMMENT (COMMENT_NO, MEMBER_ID,POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (FREC_POST_NO.NEXTVAL, 'Rocomi', 1, '첫 번째 자유 게시판 댓글입니다.', SYSDATE, 'Y');

INSERT INTO FREE_COMMENT (COMMENT_NO, MEMBER_ID,POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (FREC_POST_NO.NEXTVAL, 'Download', 2, '두 번째 자유 게시판 댓글입니다.', SYSDATE, 'Y');

INSERT INTO FREE_COMMENT (COMMENT_NO, MEMBER_ID,POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (FREC_POST_NO.NEXTVAL, '2weeks', 3, '세 번째 자유 게시판 댓글입니다.', SYSDATE, 'Y');

INSERT INTO FREE_COMMENT (COMMENT_NO, MEMBER_ID,POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (FREC_POST_NO.NEXTVAL, 'Zeus', 4, '네 번째 자유 게시판 댓글입니다.', SYSDATE, 'Y');

INSERT INTO FREE_COMMENT (COMMENT_NO, MEMBER_ID,POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (FREC_POST_NO.NEXTVAL, 'test1', 5, '다섯 번째 자유 게시판 댓글입니다.', SYSDATE, 'Y');

-- PROJECT_COMMENT 데이터 삽입
INSERT INTO PROJECT_COMMENT (COMMENT_NO, MEMBER_ID, POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROC_POST_NO.NEXTVAL, 'Rocomi', 1, '첫 번째 프로젝트 댓글입니다.', SYSDATE, 'Y');

INSERT INTO PROJECT_COMMENT (COMMENT_NO, MEMBER_ID, POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROC_POST_NO.NEXTVAL, 'Download', 2, '두 번째 프로젝트 댓글입니다.', SYSDATE, 'Y');

INSERT INTO PROJECT_COMMENT (COMMENT_NO, MEMBER_ID, POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROC_POST_NO.NEXTVAL, '2weeks', 3, '세 번째 프로젝트 댓글입니다.', SYSDATE, 'Y');

INSERT INTO PROJECT_COMMENT (COMMENT_NO, MEMBER_ID, POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROC_POST_NO.NEXTVAL, 'Zeus', 4, '네 번째 프로젝트 댓글입니다.', SYSDATE, 'Y');

INSERT INTO PROJECT_COMMENT (COMMENT_NO, MEMBER_ID, POST_NO, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROC_POST_NO.NEXTVAL, 'test1', 5, '다섯 번째 프로젝트 댓글입니다.', SYSDATE, 'Y');

-- ENQUIRY_COMMENT 데이터 삽입
INSERT INTO ENQUIRY_COMMENT (COMMENT_NO, POST_NO, MEMBER_ID, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROE_POST_NO.NEXTVAL, 1, 'Rocomi', '첫 번째 문의 게시판 댓글입니다.', SYSDATE, 'Y');

INSERT INTO ENQUIRY_COMMENT (COMMENT_NO, POST_NO, MEMBER_ID, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROE_POST_NO.NEXTVAL, 2, 'Download', '두 번째 문의 게시판 댓글입니다.', SYSDATE, 'Y');

INSERT INTO ENQUIRY_COMMENT (COMMENT_NO, POST_NO, MEMBER_ID, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROE_POST_NO.NEXTVAL, 3, '2weeks', '세 번째 문의 게시판 댓글입니다.', SYSDATE, 'Y');

INSERT INTO ENQUIRY_COMMENT (COMMENT_NO, POST_NO, MEMBER_ID, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROE_POST_NO.NEXTVAL, 4, 'Zeus', '네 번째 문의 게시판 댓글입니다.', SYSDATE, 'Y');

INSERT INTO ENQUIRY_COMMENT (COMMENT_NO, POST_NO, MEMBER_ID, COMMENT_TEXT, COMMENT_TIME, STATUS)
VALUES (PROE_POST_NO.NEXTVAL, 5, 'test1', '다섯 번째 문의 게시판 댓글입니다.', SYSDATE, 'Y');

COMMIT;
