INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, EMAIL, PHONE, BIRTH, ADDRESS, STATUS, P_IMG)
VALUES ('Rocomi', '1234', '엄희윤', 'rocomi@gmail.com', '010-1xxx-xxxx', TO_DATE('2000-01-01', 'YYYY-MM-DD'), '역삼', 'A', 'TEST.IMG');

INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, EMAIL, PHONE, BIRTH, ADDRESS, STATUS, P_IMG)
VALUES ('Download', '1234', '기다운', 'download@gmail.com', '010-2xxx-xxxx', TO_DATE('2000-01-01', 'YYYY-MM-DD'), '구로', 'A', 'TEST.IMG');

INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, EMAIL, PHONE, BIRTH, ADDRESS, STATUS, P_IMG)
VALUES ('2weeks', '1234', '이주원', '2weeks@gmail.com', '010-3xxx-xxxx', TO_DATE('2000-01-01', 'YYYY-MM-DD'), '평택', 'A', 'TEST.IMG');

INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, EMAIL, PHONE, BIRTH, ADDRESS, STATUS, P_IMG)
VALUES ('Zeus', '1234', '양준혁', 'zeus@gmail.com', '010-4xxx-xxxx', TO_DATE('2000-01-01', 'YYYY-MM-DD'), '평택', 'A', 'TEST.IMG');

INSERT INTO MEMBER (MEMBER_ID, MEMBER_PWD, MEMBER_NAME, EMAIL, PHONE, BIRTH, ADDRESS, STATUS, P_IMG)
VALUES ('test1', '1234', '테스트', 'rocomi1@gmail.com', '010-12xx-xxxx', TO_DATE('2000-01-01', 'YYYY-MM-DD'), '역삼', 'Y', 'TEST.IMG');

SELECT * FROM MEMBER;

SELECT * FROM MEMBER
        WHERE MEMBER_ID = 'Rocomi' AND MEMBER_PWD = 1234;
        
COMMIT;


