DROP TABLE CUSTOMER;
DROP TABLE RECEIPT;
DROP TABLE CUST_LEVEL;
DROP TABLE ERROR_POST;
DROP TABLE POST;
DROP TABLE COMENT;
DROP TABLE EMPLOYEE;

DROP SEQUENCE SEQ_RECEIPT_NO;
DROP SEQUENCE SEQ_ERROR_NO;
DROP SEQUENCE SEQ_POST_NO;
DROP SEQUENCE SEQ_COMENT_NO;
DROP SEQUENCE SEQ_EMP_NO;

CREATE TABLE  CUSTOMER(
	CUST_ID	VARCHAR2(20) PRIMARY KEY,
	CUST_PWD	VARCHAR2(30) NOT NULL,
	CUST_NAME	VARCHAR2(12) NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE NOT NULL,
    PHONE VARCHAR2(19) UNIQUE NOT NULL,
	BIRTH	DATE NOT NULL,
	ADDRESS	VARCHAR2(200) NOT NULL,
	RECEIPT_NO	NUMBER NOT NULL,
	STATUS	VARCHAR2(1)	NOT NULL,
	PAY_STATUS	VARCHAR2(1) NOT NULL,
	CUST_GRADE	NUMBER	NOT NULL
);
CREATE SEQUENCE SEQ_RECEIPT_NO;
CREATE TABLE RECEIPT (
	RECEIPT_NO	NUMBER	PRIMARY KEY,
	RECEIPT_CONTENTS	VARCHAR2(1000) NOT	NULL,
	RECIPT_DATE	DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) NOT NULL,
	CUSTID	VARCHAR2(20)	NOT NULL,
	CUST_GRADE	NUMBER NOT	NULL
);

CREATE TABLE CUST_LEVEL (
	CUST_GRADE	NUMBER PRIMARY KEY,
	CUST_ID REFERENCES CUSTOMER
);

CREATE SEQUENCE SEQ_ERROR_NO;
CREATE TABLE ERROR_POST (
	ERROR_NO	NUMBER	PRIMARY KEY,
	ERROR_TITLE	VARCHAR2(50)	NULL,
	ERROR_CONTENTS	VARCHAR2(4000)	NULL,
	ERROR_DATE	DATE	NULL,
	STATUS	VARCHAR(255)	NULL,
    CUST_ID REFERENCES CUSTOMER,
	EMP_ID	NUMBER	NOT NULL
);

CREATE SEQUENCE SEQ_POST_NO;
CREATE TABLE POST (
	POST_NO	NUMBER	PRIMARY KEY,
	POST_GROUP	VARCHAR2(25) NOT NULL,
	POST_TITLE	VARCHAR2(100) NOT NULL,
	POST_CONTENT	VARCHAR2(4000) NOT NULL,
	IMG_FILE	VARCHAR2(300) NOT NULL,
	POST_TIME	DATE DEFAULT SYSDATE,
	COUNT	NUMBER	NULL,
	RECOMENT	NUMBER	NULL,
    CUST_ID REFERENCES CUSTOMER
);

CREATE SEQUENCE SEQ_COMENT_NO;
CREATE TABLE COMENT (
	COMENT_NO	NUMBER	NULL,
	CONMENT_CONTENT	VARCHAR2(300)	NULL,
    CUST_ID REFERENCES CUSTOMER,
	POST_NO	NUMBER	NOT NULL
);

CREATE SEQUENCE SEQ_EMP_NO;
CREATE TABLE EMPLOYEE (
	EMP_NO	NUMBER	PRIMARY KEY,
	EMP_NAME	VARCHAR2(20)	NULL,
	JOB_RANK	CHAR(2)	NULL,
	DEPARTMENT	VARCHAR2(30)	NULL,
	PHONE	VARCHAR2(12)	NULL,
	EMAIL	VARCHAR2(25)	NULL,
	SSN 	CHAR(14)	NULL,
	ADRRESS	VARCHAR2(50)	NULL
);

