INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(1, 'Download', 'CARD', 'VIP1', 1000, TO_DATE('2024-09-19', 'YYYY-MM-DD'), 'Y');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(2, 'Download', 'CARD', 'VIP3', 199900, TO_DATE('2024-09-19', 'YYYY-MM-DD'), 'Y');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(3, 'Zeus', 'CARD', 'VIP2', 49900, TO_DATE('2024-10-19', 'YYYY-MM-DD'), 'Y');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(4, '2weeks', 'CARD', 'VIP3', 199900, TO_DATE('2024-10-19', 'YYYY-MM-DD'), 'N');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(5, '2weeks', 'CARD', 'VIP1', 1000, TO_DATE('2024-11-19', 'YYYY-MM-DD'), 'Y');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(6, 'Rocomi', 'CARD', 'VIP3', 19900, TO_DATE('2024-11-19', 'YYYY-MM-DD'), 'Y');

commit;
