INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(1, 'Download', 'CARD', 'VIP3', 199900, TO_DATE('2024-09-19', 'YYYY-MM-DD'), 'Y');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(2, 'Zeus', 'CARD', 'VIP3', 199900, TO_DATE('2024-10-19', 'YYYY-MM-DD'), 'Y');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(3, '2weeks', 'CARD', 'VIP3', 199900, TO_DATE('2024-10-19', 'YYYY-MM-DD'), 'Y');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(4, 'Rocomi', 'CARD', 'VIP3', 199000, TO_DATE('2024-11-19', 'YYYY-MM-DD'), 'Y');

INSERT INTO PAYMENT (PAY_ID, MEMBER_ID, PAY_METHOD, PAY_PRODUCT, PAY_PRICE, PAY_TIME, PAY_STATUS) VALUES
(5, 'test1', 'CARD', 'VIP3', 199000, TO_DATE('2024-11-19', 'YYYY-MM-DD'), 'N');

commit;
